package com.aiuta.fashionsdk.configuration.features.models.images

/**
 * Enum defining the ownership type of images in the SDK.
 * 
 * This enum is used to distinguish between user-provided images and
 * Aiuta images in the SDK's image processing pipeline.
 * 
 * @property USER Images provided by the user
 * @property AIUTA Images generated by the Aiuta
 */
public enum class AiutaOwnerType {
    USER,
    AIUTA,
}
