name: Publish to Maven central

on:
    release:
        types: [ published ]

concurrency:
    group: release-manual-maven-${{ github.ref }}
    cancel-in-progress: true

jobs:
    release_on_maven:
        name: Release on Maven Central
        runs-on: macos-latest

        timeout-minutes: 180

        steps:
            -   name: Checkout
                uses: actions/checkout@v4
                with:
                    fetch-depth: 0

            -   name: Base setup
                uses: ./.github/actions/setup-base

            -   name: Set release version
                id: set_release_version
                run: |
                    bash ./scripts/update_version.sh ${{ github.event.release.name }}

            -   name: Setup gradle
                uses: gradle/actions/setup-gradle@v4

            -   name: Release on maven central
                env:
                    ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.MAVENCENTRAL_SONATYPE_USERNAME }}
                    ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.MAVENCENTRAL_SONATYPE_PASSWORD }}
                    ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.MAVENCENTRAL_GPG_KEY }}
                    ORG_GRADLE_PROJECT_signingInMemoryKeyId: ${{ secrets.MAVENCENTRAL_GPG_KEY_ID }}
                    ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.MAVENCENTRAL_GPG_KEY_PASSWORD }}
                run: ./gradlew publishAndReleaseToMavenCentral --no-configuration-cache
